사물함 예약 기능 추가
EATSTEAK/lockerweb pull request #199
Opened 2022-09-06 19:56 UTC by Twince

## 사물함 예약 기능 추가
- 예약 페이지에서 사물함을 클릭하여 예약 가능
- 예약 로딩 화면 단위에서 예약하는 사물함 표기
- 예약 완료 시 프로필 및 내 사물함 정보 `refresh`
- `SelectedLockerAlert` - backdrop blur 추가

2022-09-06 20:33 UTC, EATSTEAK requested changes
indent 가 왜 4칸이 되었을까요?

2022-09-07 07:26 UTC, Twince commented
저장하면서 prettier 적용이 안된 것 같습니다.

2022-09-07 09:52 UTC, EATSTEAK requested changes
인덴트가 안고쳐지고 탭 문자가 들어갔네요...

2022-09-07 10:03 UTC, EATSTEAK approved these changes

2022-09-07 10:03 UTC, merged